# The drone config
kind: pipeline
type: docker
name: for dev test

steps:
  # build the application to ./dist/app
  - name: build app
    image: golang:1.15
    volumes:
      - name: go-cache
        path: /go/pkg
    environment:
      GOCACHE: /go/pkg/.cache/go-build/edge-backend
      GOPROXY: https://goproxy.io
      GO111MODULE: on
    commands:
      - make drone-build

  # for daocloud harbor
  - name: for harbor - dao cloud
    image: plugins/docker
    pull: if-not-exists
    settings:
      username:
        from_secret: daocloud_harbor_name
      password:
        from_secret: daocloud_harbor_secret
      dockerfile: dockerfile
      repo: harbor.daocloud.cn/xudong.meng/example
      registry: harbor.daocloud.cn
      tags:
        drone-test-${DRONE_BUILD_NUMBER}