apiVersion: v1
kind: Namespace
metadata:
  name: example
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example
    service: example
  name: example
  namespace: example
spec:
  ports:
    - name: http-gin
      port: 3000
      protocol: TCP
      targetPort: 3000
    - name: tcp-mock
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: example
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example
    version: v1
  name: example
  namespace: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
      version: v1
  template:
    metadata:
      labels:
        app: example
        version: v1
    spec:
      containers:
        - image: harbor.daocloud.cn/xudong.meng/example:drone-test-7
          imagePullPolicy: IfNotPresent
          name: example
          ports:
            - containerPort: 3000
              protocol: TCP
            - containerPort: 8000
              protocol: TCP